# Generated by Django 4.0.5 on 2022-06-16 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
            ],
        ),
    ]
