# Generated by Django 4.0.5 on 2022-06-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progetto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='saldo',
            field=models.FloatField(default=0.0, max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
