# Generated by Django 4.0.5 on 2022-06-23 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progetto', '0003_transaction_rename_saldo_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
